version: '3.8'
services:
  web:
    image: nginx:alpine
    container_name: finance-web
    ports:
      - "8080:80"
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: finance-api
    environment:
      - PORT=4000
      - LEDGER_URL=http://ledger:5000/validate
    ports:
      - "4000:4000"
    depends_on:
      - ledger
  ledger:
    build:
      context: .
      dockerfile: ledger/Dockerfile
    container_name: finance-ledger
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
  db:
    image: postgres:15-alpine
    container_name: finance-db
    environment:
      - POSTGRES_USER=finance
      - POSTGRES_PASSWORD=finance
      - POSTGRES_DB=finance
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
