name: CI - Tests unitaires et E2E

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit/integration tests (Jest)
        run: npm test -- --ci

      - name: Start PHP server (serving build)
        run: php -S 127.0.0.1:5173 -t finance-flow/build &

      - name: Wait for server
        run: npx wait-on http://127.0.0.1:5173

      - name: Run Cypress E2E
        run: npm run test:e2e
